[phases.setup]
nixPkgs = ["php", "phpPackages.pdo", "phpPackages.pdo_pgsql", "phpPackages.pdo_mysql", "composer"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
